<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PegawaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pegawai')->insert([
            [
                'nip' => '197405161999031001',
                'nama' => 'HENDERY DAHLAN',
                'gelar_depan' => '',
                'gelar_belakang' => 'M.Sc., Ph.D.',
                'status' => 'AKTIF',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Salat Panjang',
                'tanggal_lahir' => '1974-05-16',
                'agama_id' => 1,
                'jenis_kepegawaian_id' => 1,
                'kategori_kepegawaian_id' => 1,
                'departemen_id' => 54,
                'kepangkatan_id' => 12,
            ],
            [
                'nip'=>'197410282008011006',
                'nama'=>'ABDUL KHALIQ',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., MA',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Siluak Panjang',
                'tanggal_lahir'=>'1974-10-28',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'12',
            ],
            [
                'nip'=>'199510252024061001',
                'nama'=>'ADIB',
                'gelar_depan'=>'',
                'gelar_belakang'=>'S.E.,M.E.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Tanah Datar',
                'tanggal_lahir'=>'1995-10-25',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'63',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198804162019032013',
                'nama'=>'ADILA ADISTI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'S.E., M.Ec.ME',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1988-04-16',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'199107052019031015',
                'nama'=>'AGRI QISTHI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., MM',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1991-07-05',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'197508202001121001',
                'nama'=>'ALFITMAN',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE. M.Sc',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1975-08-20',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'64',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'196302051993031001',
                'nama'=>'ALINURSAL NOER',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE, MM',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1963-02-05',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'16',
            ],
            [
                'nip'=>'196010041987021003',
                'nama'=>'AMRA AUSRI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Kampani Barangan, Pariaman',
                'tanggal_lahir'=>'1960-10-04',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'12',
            ],
            [
                'nip'=>'199304092024061001',
                'nama'=>'ANAN WEIRDIE WIRAWAN ',
                'gelar_depan'=>'',
                'gelar_belakang'=>'S.E., M.S.AK.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Pekan Baru',
                'tanggal_lahir'=>'1993-04-09',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'62',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198309122005012002',
                'nama'=>'ANNISAA RAHMAN',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., Akt., MS',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Pariaman',
                'tanggal_lahir'=>'1983-09-12',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'199009152019031017',
                'nama'=>'ARES ALBIRRU AMSAL',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.S.M',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1990-09-15',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198607092014041001',
                'nama'=>'ARIE SUKMA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Sc.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1986-07-09',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198712162014041001',
                'nama'=>'ARIEF PRIMA JOHAN',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Sc',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1987-12-16',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'64',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'196904091994031001',
                'nama'=>'ARIES TANNO',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., Akt. M.Si',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1969-04-09',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'14',
            ],
            [
                'nip'=>'199306012024061001',
                'nama'=>'ARIO HERNEST HADINATA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Ogan Komering Ulu',
                'tanggal_lahir'=>'1993-06-01',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'63',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'196010102006041001',
                'nama'=>'ASMI A',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., MM',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang Panjang',
                'tanggal_lahir'=>'1960-10-10',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'196508071991032002',
                'nama'=>'ASNIATI',
                'gelar_depan'=>'Dr.Dra.',
                'gelar_belakang'=>'Akt., MBA., CA., CSRA',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Kamang, Agam',
                'tanggal_lahir'=>'1965-08-07',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'14',
            ],
            [
                'nip'=>'199511122024061001',
                'nama'=>'AULIA PUJA ILHAM',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE, M.E',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1995-11-12',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'62',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'199504012024061002',
                'nama'=>'BAITUL HAMDI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'S.E.,M.SEI.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang Panjang',
                'tanggal_lahir'=>'1995-01-01',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'199301242024061002',
                'nama'=>'BELLIGO AGRA',
                'gelar_depan'=>'',
                'gelar_belakang'=>' S.E.,M.Sc.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1993-01-24',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198506152019031009',
                'nama'=>'BERRI BRILLIANT ALBAR',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE, MM',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1985-06-15',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'199011172019032019',
                'nama'=>'BESTI NOVIANDA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.S.E',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1990-11-17',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198208232005012001',
                'nama'=>'BETTY USPRI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Batusangkar',
                'tanggal_lahir'=>'1982-08-23',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'9',
            ],
            [
                'nip'=>'198801022018031001',
                'nama'=>'BINTANG RIZKY ABDULLAH MAJO SAIBAH',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1988-01-02',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'199307132019032013',
                'nama'=>'CHAIRUNNISYA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.M',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1993-07-13',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'199104262019031009',
                'nama'=>'DANNY HIDAYAT',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE, MM',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Tanah Datar',
                'tanggal_lahir'=>'1991-04-26',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'64',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'197611062007012001',
                'nama'=>'DELFIA TANJUNG SARI',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1976-11-06',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198003272006042001',
                'nama'=>'DENNY YOHANA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., Akt. M.Si',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1980-03-27',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'12',
            ],
            [
                'nip'=>'198012112005012002',
                'nama'=>'DESSY KURNIA SARI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Bus., Ph.D.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Pariaman',
                'tanggal_lahir'=>'1980-12-11',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'12',
            ],
            [
                'nip'=>'196612191992032001',
                'nama'=>'DESYETTI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., MM',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1966-12-19',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'199307282019032017',
                'nama'=>'DEVI YULIA RAHMI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'S.E., M.Sc',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Agam',
                'tanggal_lahir'=>'1993-07-28',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198109082005012004',
                'nama'=>'DIAN RANI YOLANDA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Buss.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1981-09-08',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'9',
            ],
            [
                'nip'=>'199206122018032001',
                'nama'=>'DIAN YUNI ANGGRAENI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE.I., M.SA.,Ak.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Jakarta',
                'tanggal_lahir'=>'1992-06-12',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198011122005011003',
                'nama'=>'DONARD GAMES',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Bus., Ph.D.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Batusangkar',
                'tanggal_lahir'=>'1980-11-12',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'14',
            ],
            [
                'nip'=>'195710101986091001',
                'nama'=>'EDDY R. RASYID',
                'gelar_depan'=>'Prof. Dr. Drs.',
                'gelar_belakang'=>'SE, M.Com(Hons),Ph.D,Akt',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1957-10-10',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'17',
            ],
            [
                'nip'=>'197402241999031001',
                'nama'=>'EDI ARIYANTO',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., M.Si',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Pekanbaru, Riau',
                'tanggal_lahir'=>'1974-02-24',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'197205021996021001',
                'nama'=>'EFA YONNEDI',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., M.PPM, Ak',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Jopang Manganti, Lima Puluh Kota',
                'tanggal_lahir'=>'1972-05-02',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'15',
            ],
            [
                'nip'=>'196210201987021003',
                'nama'=>'ELFINDRI',
                'gelar_depan'=>'Prof. Dr.',
                'gelar_belakang'=>'SE., MA',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1962-10-24',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'17',
            ],
            [
                'nip'=>'198604042024062001',
                'nama'=>'ELVINA PRIMAYESA',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'S.E., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Sungai Penuh',
                'tanggal_lahir'=>'1986-04-04',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'196505071991032003',
                'nama'=>'ELVIRA LUTHAN',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., Akt. M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1965-05-07',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'14',
            ],
            [
                'nip'=>'197209271998021001',
                'nama'=>'ENDRIZAL RIDWAN',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.EC., Ph.D',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Tanjung Gadang Rumah, 50 Kota',
                'tanggal_lahir'=>'1972-09-27',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'63',
                'kepangkatan_id'=>'12',
            ],
            [
                'nip'=>'197202101999032003',
                'nama'=>'ERI BESRA',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., MM',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1972-02-10',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'196610181993031001',
                'nama'=>'ERIZAL N',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., MM',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Alahan Sabatang',
                'tanggal_lahir'=>'1966-10-18',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'12',
            ],
            [
                'nip'=>'197712062008012012',
                'nama'=>'ERNA WIDIASTUTY',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Si',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Mataram',
                'tanggal_lahir'=>'1977-12-26',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'197905132006041014',
                'nama'=>'FAISAL ALI AHMAD',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SP., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1979-05-13',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198005292005011003',
                'nama'=>'FAJRI ADRIANTO',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Bus., Ph.D.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Dalam Koto Taeh',
                'tanggal_lahir'=>'1980-05-29',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'197601042002121002',
                'nama'=>'FAJRI MUHARJA',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., MS.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Pasir Lawas, Tanah Datar',
                'tanggal_lahir'=>'1976-01-04',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'198605242019032013',
                'nama'=>'FATMA PONI MARDIAH',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., MSM',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1986-05-24',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'64',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198107172005011002',
                'nama'=>'FAUZAN MISRA',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., Akt., M.Sc.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Alur Tengah, Batu Bulat, Tanah Datar',
                'tanggal_lahir'=>'1981-07-17',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'197702062005011001',
                'nama'=>'FEBRIANDI PRIMA PUTRA',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., M.Si',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1977-02-06',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'9',
            ],
            [
                'nip'=>'197302061999031002',
                'nama'=>'FERY ANDRIANUS',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1973-02-06',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'14',
            ],
            [
                'nip'=>'197507272001121004',
                'nama'=>'FIRDAUS',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., Akt. M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Pariaman',
                'tanggal_lahir'=>'1975-07-27',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'199005092024062001',
                'nama'=>'FITRIA KHAIRINA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'M.M.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1990-05-09',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'199405122024062001',
                'nama'=>'GHINA SAKINAH ',
                'gelar_depan'=>'',
                'gelar_belakang'=>'M.E.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1994-05-12',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'199204172022032008',
                'nama'=>'FITRIYENI OKTAVIA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'S.E., M.Ak.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1992-04-17',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198911062024062001',
                'nama'=>'HESTY AISYAH ',
                'gelar_depan'=>'',
                'gelar_belakang'=>'S.E., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Jakarta',
                'tanggal_lahir'=>'1989-10-06',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198604052015041003',
                'nama'=>'HADI RAHADIAN',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Si',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1986-04-05',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'197303082001121001',
                'nama'=>'HAFIZ RAHMAN',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., Akt., MSBS., Ph.D',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1973-03-08',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'196202231988031001',
                'nama'=>'HAMDANI',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'MM., S.Si., Ak.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Pesisir Selatan',
                'tanggal_lahir'=>'1962-02-23',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'18',
            ],
            [
                'nip'=>'196410131991031001',
                'nama'=>'HANSASTRI',
                'gelar_depan'=>'Drs.',
                'gelar_belakang'=>'M.M.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Pasaman Barat ',
                'tanggal_lahir'=>'1964-10-13',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'65',
                'kepangkatan_id'=>'18',
            ],
            [
                'nip'=>'197102211997011001',
                'nama'=>'HARIF AMALI RIVAI',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1971-02-21',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'14',
            ],
            [
                'nip'=>'196510201993021001',
                'nama'=>'HEFRIZAL HANDRA',
                'gelar_depan'=>'Drs.',
                'gelar_belakang'=>'M.Soc.Sc., Ph.D.i',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Salido, Pesisir Selatan',
                'tanggal_lahir'=>'1965-10-20',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'64',
                'kepangkatan_id'=>'14',
            ],
            [
                'nip'=>'197106242006041007',
                'nama'=>'HENDRA LUKITO',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., MM., Ph.D.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang Panjang',
                'tanggal_lahir'=>'1971-06-24',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'12',
            ],
            [
                'nip'=>'196312151990011001',
                'nama'=>'HERRI',
                'gelar_depan'=>'Prof. Dr.',
                'gelar_belakang'=>'SE., MBA',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Payakumbuh',
                'tanggal_lahir'=>'1963-12-15',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'17',
            ],
            [
                'nip'=>'199501042024062002',
                'nama'=>'IRMA SURYANI INDRA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'S.E.,M.AK.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1995-01-04',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'196402051989012001',
                'nama'=>'HUSNA ROZA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., Akt., M.Com (HONS)',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1964-02-05',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'64',
                'kepangkatan_id'=>'12',
            ],
            [
                'nip'=>'197912162005012002',
                'nama'=>'IDAMIHARTI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Sc',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1979-12-16',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'9',
            ],
            [
                'nip'=>'199303312019032019',
                'nama'=>'IHSANI MAZELFI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Acc.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1993-03-31',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'64',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198809082019032016',
                'nama'=>'IKA SARI WAHYUNI TD',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., MSACC.,Ak.,CA',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1988-09-08',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'196205051989011001',
                'nama'=>'ILMAINIR',
                'gelar_depan'=>'Drs.',
                'gelar_belakang'=>'M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Batusangkar',
                'tanggal_lahir'=>'1962-05-05',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'198509282019032011',
                'nama'=>'INDAH MAYA SARI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1985-09-28',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198806222019032012',
                'nama'=>'INDAH PERMATA SURYANI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Sc.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang ',
                'tanggal_lahir'=>'1988-06-22',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'196407021990012002',
                'nama'=>'INDRAWARI',
                'gelar_depan'=>'Dra.',
                'gelar_belakang'=>'SE., MA., Ph.D.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Painan',
                'tanggal_lahir'=>'1964-07-02',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'12',
            ],
            [
                'nip'=>'199303192024062001',
                'nama'=>'MARETHA PRIMADYAN',
                'gelar_depan'=>'',
                'gelar_belakang'=>'',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1993-03-19',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'62',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'196212291992031001',
                'nama'=>'ISWARDI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'ST., Akt. MM',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1962-12-29',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'197806022009121001',
                'nama'=>'JAUHARRY',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., MM',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1978-06-02',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'63',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'196010211989031001',
                'nama'=>'JONHAR',
                'gelar_depan'=>'Drs.',
                'gelar_belakang'=>'Akt.MS',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Magek, Agam',
                'tanggal_lahir'=>'1960-10-21',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'12',
            ],
            [
                'nip'=>'197907022005012004',
                'nama'=>'LAELA SUSDIANI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Com',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Magelang, Jateng',
                'tanggal_lahir'=>'1979-07-02',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'9',
            ],
            [
                'nip'=>'196304041989012001',
                'nama'=>'LAKSMI DEWI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Si',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Lubuk Sikaping, Pasaman',
                'tanggal_lahir'=>'1963-04-04',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'64',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'199401262022032012',
                'nama'=>'LAURA AMELIA TRIANI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'S.E., M.M.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1994-01-26',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'195908271986032001',
                'nama'=>'LAURA SYAHRUL',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., MBA',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Palembang',
                'tanggal_lahir'=>'1959-08-27',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'15',
            ],
            [
                'nip'=>'196212041987032001',
                'nama'=>'LELI SUMARNI',
                'gelar_depan'=>'Dra.',
                'gelar_belakang'=>'M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1962-12-04',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'12',
            ],
            [
                'nip'=>'198501172019032010',
                'nama'=>'LUCIANA LUTHAN',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1985-01-17',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'63',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198302172009121002',
                'nama'=>'LUCKY MAHESA YAHYA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., MM',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1983-02-17',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'196411231993031001',
                'nama'=>'LUKMAN',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., MS',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Muko Jalan, Agam',
                'tanggal_lahir'=>'1964-11-23',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'199207082024062001',
                'nama'=>'MELIA YULIANTI ',
                'gelar_depan'=>'',
                'gelar_belakang'=>'S.S.T., M.AK.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Pasaman Barat',
                'tanggal_lahir'=>'1992-07-08',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'197706232000121001',
                'nama'=>'MA RUF',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., M.Bus., M.Phil.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Ladang Darek, Agam',
                'tanggal_lahir'=>'1977-06-23',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'63',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'198003252007012001',
                'nama'=>'MARYANTI',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., M.Si',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1980-03-25',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'196909031995121001',
                'nama'=>'MASYHURI HAMIDI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Si., Ph.D.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Batipuh Baruh, Tanah Datar',
                'tanggal_lahir'=>'1969-09-03',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'14',
            ],
            [
                'nip'=>'199412052024062003',
                'nama'=>'NADIA FAZIRA ',
                'gelar_depan'=>'',
                'gelar_belakang'=>'M.Sc.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1994-12-05',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'63',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'199108072024062001',
                'nama'=>'NOVI AMELIA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'S.E., M.E.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1991-08-07',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'62',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'198611302015042004',
                'nama'=>'MEUTHIA',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Sc.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Padang',
                'tanggal_lahir'=>'1986-11-30',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'197905272003121002',
                'nama'=>'MOHAMAD FANY ALFARISI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Sc.E., Ph.D.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Jakarta',
                'tanggal_lahir'=>'1979-05-27',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'196207151988111001',
                'nama'=>'MUHAMMAD NAZER',
                'gelar_depan'=>'Dr.Drs.',
                'gelar_belakang'=>'MA',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1962-07-15',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'14',
            ],
            [
                'nip'=>'197508212002122002',
                'nama'=>'MUSBATIQ SRIVANI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., Akt., MA',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1975-08-21',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'11',
            ],
            [
                'nip'=>'199508062024062001',
                'nama'=>'NURUL IKHSANTI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'S.E.,M.E.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Payakumbuh',
                'tanggal_lahir'=>'1995-08-06',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'2',
                'departemen_id'=>'62',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'195909121987021001',
                'nama'=>'NASRI BACHTIAR',
                'gelar_depan'=>'Prof. Dr.',
                'gelar_belakang'=>'SE., MS',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1959-09-12',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'18',
            ],
            [
                'nip'=>'198211072009122005',
                'nama'=>'NELVIA IRYANI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Bukittinggi',
                'tanggal_lahir'=>'1982-11-07',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'59',
                'kepangkatan_id'=>'10',
            ],
            [
                'nip'=>'197106272006042001',
                'nama'=>'NENG KAMARNI',
                'gelar_depan'=>'Dr.',
                'gelar_belakang'=>'SE., M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Pariaman',
                'tanggal_lahir'=>'1971-06-27',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'12',
            ],
            [
                'nip'=>'196309061990011001',
                'nama'=>'NIKI LUKVIARMAN',
                'gelar_depan'=>'Prof. Dr.',
                'gelar_belakang'=>'SE., Akt., MBA',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'L',
                'tempat_lahir'=>'Padang Panjang',
                'tanggal_lahir'=>'1963-09-06',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'61',
                'kepangkatan_id'=>'18',
            ],
            [
                'nip'=>'196902051994022001',
                'nama'=>'NINI SYOFRI YENI',
                'gelar_depan'=>'',
                'gelar_belakang'=>'SE., Akt. M.Si.',
                'status'=>'AKTIF',
                'jenis_kelamin'=>'P',
                'tempat_lahir'=>'Pasir, Agam',
                'tanggal_lahir'=>'1969-02-05',
                'agama_id'=>'1',
                'jenis_kepegawaian_id'=>'1',
                'kategori_kepegawaian_id'=>'1',
                'departemen_id'=>'60',
                'kepangkatan_id'=>'12',
            ],
        ]);
    }
}
